info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
eureka:
  instance:
    hostname: pay-provider1
    instance-id: pay-provider:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://admin:bdxh123456@eureka-server1:9001/eureka/,http://admin:bdxh123456@eureka-server2:9002/eureka/,http://admin:bdxh123456@eureka-server3:9003/eureka/
spring:
  #redis配置
  redis:
    cluster:
      nodes: 119.23.185.109:8001,119.23.185.109:8002,47.107.253.90:8003,47.107.253.90:8004,119.23.185.109:8005,47.107.253.90:8006
    timeout: 5000
    password: Bdxh_123456
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 2
    database: 0
  #rocketmq配置
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 47.107.253.90:9876;47.107.255.252:9876
#rocketmq producer配置
rocketmq:
  producer:
    defaultName: default-pay-provider #生产者组名
    transName: trans-pay-provider
    transEnable: true #是否开启事务消息
    #rocketmq producer配置
  consumer:
    groupName: default-pay-consumer #消费者组名
    topic: wechatPayWalletNotice
    tag: appmarket #多个 以 tag1,tag2
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS