spring:
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis配置
  redis:
    cluster:
      nodes: 119.23.185.109:8001,47.107.253.90:8003,47.107.255.252:8005,119.23.185.109:8002,47.107.253.90:8004,47.107.255.252:8006
    timeout: 5000
    lettuce:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 20
        max-wait: -1
    database: 0
#httpPoolClient配置
httpPool:
  maxTotal: 3000
  maxPerRoute: 100
  connectRequestTimeout: 3000
  connectTimeout: 5000
  socketTimeout: 10000
  enable: false
#netty配置
netty:
  tcpPort: 9030
  bossCount: 2
  workerCount: 4
  keepAlive: true
  backlog: 200