info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
server:
  port: 9031
spring:
  application:
    name: appburied-provider-cluster
  profiles:
    active: dev
    #spring框架时间比京八区标准时间差八小时(time-zone一定不能少)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#apollo配置
app:
  id: appburied-provider-cluster1
apollo:
  meta: http://47.107.253.90:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: BASE.public.eureka,BASE.public-hikari-ds,application,BASE.public-redis

#日志
logging:
  config: classpath:logback-spring.xml

